Repository Friends77/FRI-FRONT, pull requests merged in 2024-12, with the labels that each got.

#11 Deploy/모든 경로 요청 Redirect to root
  vercel.json
Labels: ⚙️Chore

#9 Route/router 구축
  package-lock.json
  package.json
  src/App.tsx
  src/constants/.gitkeep
  src/constants/common/path.ts
  src/main.tsx
  src/pages/.gitkeep
  src/routes/AppRouter.tsx
Labels: ✨feature

#7 취약점 해결, axios, tsconfig 설정
  .github/ISSUE_TEMPLATE/fe-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  src/apis/@core/index.ts
  tsconfig.json
Labels: ⚙️Chore

#15 Chore/절대 경로 alias 추가
  src/routes/AppRouter.tsx
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️Chore

#19 로그인 후 토큰 저장 및 로그인 상태 관리
  package-lock.json
  package.json
  src/apis/auth/index.ts
  src/hooks/auth/index.ts
  src/recoil/isLoggedIn/atom.ts
  src/recoil/isLoggedIn/index.ts
  src/types/auth/index.ts
  src/utils/cookie.ts
Labels: ✨feature

#22 공통 컴포넌트 생성#21
  src/apis/.gitkeep
  src/components/.gitkeep
  src/components/@common/Button/Button.tsx
  src/components/@common/Input/Input.tsx
  src/components/signup/Timer/Timer.tsx
  src/hooks/.gitkeep
  src/hooks/useInput.ts
  src/utils/.gitkeep
  src/utils/formatter/time/index.tsx
  src/utils/validation/input/index.tsx
Labels: ✨feature

#24 로그인 에러 처리
  src/constants/message/index.ts
  src/hooks/auth/index.ts
  src/pages/login/index.tsx
Labels: ✨feature, 📫API

#25 이메일 회원가입#1
  src/apis/auth/index.ts
  src/components/@common/Button/Button.tsx
  src/components/@common/Input/Input.tsx
  src/components/signup/Form/AuthForm.tsx
  src/components/signup/Form/ProfileForm.tsx
  src/components/signup/Input/InputField.tsx
  src/components/signup/Timer/Timer.tsx
  src/constants/message/index.ts
  src/constants/pattern/index.ts
  src/constants/routes/index.ts
  src/hooks/useInput.ts
  src/pages/.gitkeep
  src/pages/auth/signUp/index.tsx
  src/pages/auth/signUpRoot/index.tsx
  src/recoil/auth/signUp/atom.ts
  src/recoil/auth/signUp/index.ts
  src/routes/AppRouter.tsx
  src/types/auth/index.ts
  src/utils/step/moveSteps.ts
  src/utils/validation/input/index.tsx
Labels: ✨feature

#26 토큰 재발급 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/apis/@core/authInstance.ts
  src/apis/@core/instance.ts
  src/apis/auth/index.ts
  src/components/authInterceptor/AuthInterceptor.tsx
  src/components/tokenRefresher/TokenRefresher.tsx
  src/hooks/auth/useLogin.ts
  src/hooks/auth/useRefresh.ts
  src/pages/login/index.tsx
  src/recoil/auth/accessToken/atom.ts
  src/recoil/auth/accessToken/index.ts
  src/recoil/auth/accessToken/withIsLoggedIn.ts
  src/recoil/isLoggedIn/atom.ts
  src/recoil/isLoggedIn/index.ts
  src/utils/cookie.ts
Labels: ✨feature, 📫API

#30 ImagePicker 컴포넌트 생성#27
  src/components/auth/Form/AuthForm/index.tsx
  src/components/auth/Form/ProfileForm/index.tsx
  src/components/auth/ImagePicker/index.tsx
  src/components/auth/Input/index.tsx
  src/components/auth/Timer/index.tsx
  src/pages/auth/signUp/index.tsx
Labels: ✨feature

#32 비밀번호 찾기/변경 페이지 구현
  src/apis/auth/index.ts
  src/components/auth/Form/AuthForm/index.tsx
  src/components/auth/Form/EmailVerificationForm/index.tsx
  src/components/auth/Form/ResetPasswordForm/index.tsx
  src/constants/routes/index.ts
  src/hooks/auth/useResetPassword.ts
  src/hooks/auth/useSendCodeToEmail.ts
  src/hooks/auth/useVerifyCode.ts
  src/pages/auth/resetPassword/index.tsx
  src/recoil/auth/emailAuthToken/atom.ts
  src/recoil/auth/emailAuthToken/index.ts
  src/recoil/auth/resetPassword/atom.ts
  src/recoil/auth/resetPassword/index.ts
  src/routes/AppRouter.tsx
  src/types/auth/index.ts
Labels: ✨feature, 📫API

#38 Add prettier config#37
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
Labels: ⚙️chore

#36 프로젝트 전역 테마 설정#35
  package-lock.json
  package.json
  src/assets/.gitkeep
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/index.css
  src/main.tsx
  src/styles/.gitkeep
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: ✨feature

#39 소셜 로그인 기능 개발
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth/index.ts
  src/components/auth/Form/LoginForm/index.tsx
  src/components/auth/Form/SocialLoginForm/index.tsx
  src/constants/auth/index.ts
  src/constants/routes/index.ts
  src/hooks/auth/useSocialLogin.ts
  src/pages/auth/callback/google/index.tsx
  src/pages/auth/callback/naver/index.tsx
  src/pages/auth/login/index.tsx
  src/recoil/auth/socialLogin/atom.ts
  src/recoil/auth/socialLogin/index.ts
  src/routes/AppRouter.tsx
  src/types/auth/index.ts
Labels: ✨feature, 📫API

#41 공통 컴포넌트: checkbox, radio 생성
  src/assets/icons/check-mark.svg
  src/components/@common/Checkbox/Checkbox.styled.ts
  src/components/@common/Checkbox/index.tsx
  src/components/@common/Radio/Radio.styled.ts
  src/components/@common/Radio/index.tsx
Labels: ✨feature

#43 소셜 로그인 디자인, SVG 공통 컴포넌트 생성
  src/components/@common/SVG/Icon/GoogleLogin.tsx
  src/components/@common/SVG/Icon/NaverLogin.tsx
  src/components/@common/SVG/index.tsx
  src/components/auth/Form/SocialLoginForm/SocialLoginForm.styled.ts
  src/components/auth/Form/SocialLoginForm/index.tsx
  src/main.tsx
  src/styles/GlobalStyle.ts
  src/styles/GlobalStyle.tsx
Labels: ✨feature, 🎨style
