Repository Friends77/FRI-FRONT, pull requests merged in 2025-03, with the labels that each got.

#115 마이페이지 수정 시 UI 오류 수정
  src/pages/user/profile/index.tsx
Labels: 🐞bugfix

#118 자동 배포 설정
  .github/workflows/deploy.yml
Labels: ⚙️chore

#119 deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 🐞bugfix

#122 chore: ci/cd를 docker 함께 수정
  .github/workflows/deploy.yml
  Dockerfile
Labels: ⚙️chore

#120 홈 화면 내 친구 찾아보기 섹션 수정
  src/apis/@common/index.ts
  src/components/@common/Recommendations/User/RecommendedUsers/index.tsx
  src/components/@common/Recommendations/User/UserCard/UserCard.styled.ts
  src/components/@common/Recommendations/User/UserCard/index.tsx
  src/hooks/@common/useGetRecommendedUsers.ts
  src/hooks/@common/usePrivateRecommendations.ts
  src/hooks/@common/usePublicRecommendations.ts
  src/types/@common/index.ts
Labels: 🐞bugfix, 🔨refactor

#131 refactor: 채팅방 카드 min-height 지정
  src/components/home/ChatRoomCard/ChatRoomCard.styled.ts
Labels: 🔨refactor

#132 refactor: 채팅방 추천 카드 한 줄 소개 line-clamp 적용
  src/components/home/ChatRoomCard/ChatRoomCard.styled.ts
Labels: 🔨refactor

#133 refactor: 스타일 관련 리팩터링
  src/components/@common/Form/Dropdown/index.tsx
  src/pages/home/index.tsx
  src/pages/user/profile/ProfilePage.styled.ts
  src/pages/user/profile/index.tsx
Labels: 🔨refactor

#135 fix: 프로필 다이얼로그 성별 버그 수정
  src/components/@common/Modal/ProfileDialog/index.tsx
  src/components/@layout/SideBar/WithoutAuth/WithoutAuth.styled.ts
  src/components/home/Banner/Banner.styled.ts
  src/components/home/Banner/index.tsx
  src/components/home/Recommendations/User/RecommendedUsers/RecommendedUsers.styled.ts
  src/pages/home/home.styled.ts
Labels: 🐞bugfix
